[package]
name = 'slasher'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bls = { workspace = true }
database = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
eth1_api = { workspace = true }
features = { workspace = true }
futures = { workspace = true }
helper_functions = { workspace = true }
tracing = { workspace = true }
logging = { workspace = true }
p2p = { workspace = true }
serde = { workspace = true }
ssz = { workspace = true }
thiserror = { workspace = true }
types = { workspace = true }

[dev-dependencies]
unwrap_none = { workspace = true }
