[package]
name = 'http_api_utils'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
features = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
mime = { workspace = true }
parse-display = { workspace = true }
prometheus_metrics = { workspace = true }
thiserror = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
