[package]
name = 'eip_7594'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
kzg_utils = { workspace = true }
kzg = { workspace = true }
ssz = { workspace = true}
c-kzg = {workspace = true}
tiny-keccak = {workspace = true}
sha3 = {workspace = true}