[package]
name = 'serde_utils'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
generic-array = { workspace = true }
hex = { workspace = true }
hex_fmt = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
try_from_iterator = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
ssz = { workspace = true }
test-case = { workspace = true }
