[package]
name = 'directories'
version = '0.1.0'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
fs_extra = { workspace = true }
types = { workspace = true }
