[package]
name = 'zkvm_guest_pico'
edition = "2024"
version = "0.1.0"
authors = ["Grandine <info@grandine.io>"]

[workspace]

[dependencies]
anyhow = '1.0.93'
bls = { path = '../../../bls', features = ['zkcrypto'] }
# Even though there is a warning message during compilation saying the crate is not used,
# this package is used by `bls` and need `zkvm-pico` feature activated.
bls-zkcrypto = { path = '../../../bls/bls-zkcrypto', features = ['zkvm-pico'] }
enum-iterator = '2'
pico-sdk = { git = "https://github.com/brevis-network/pico.git", tag = "v1.1.7" }
pubkey_cache = { path = '../../../pubkey_cache' }
serde = { version = "1.0", features = ["derive"] }
ssz = { path = '../../../ssz' }
transition_functions = { path = '../../../transition_functions' }
types = { path = '../../../types' }

# Specify sha2 library to activate `zkvm-pico` feature
sha2 = { git = 'https://github.com/grandinetech/universal-precompiles.git', tag = 'sha2-v0.10.9-up.1', features = ['compress', 'zkvm-pico'] }
